@ fastcall -stub  -arch=arm ExAcquireFastMutex(ptr)
@ fastcall -stub  -arch=arm ExReleaseFastMutex(ptr)
@ fastcall -stub  -arch=arm ExTryToAcquireFastMutex(ptr)
@ fastcall -stub  -arch=i386 ExAcquireFastMutex(ptr) ntoskrnl.ExiAcquireFastMutex
@ fastcall -stub  -arch=i386 ExReleaseFastMutex(ptr) ntoskrnl.ExiReleaseFastMutex
@ fastcall -stub  -arch=i386 ExTryToAcquireFastMutex(ptr) ntoskrnl.ExiTryToAcquireFastMutex
@ fastcall -stub  HalClearSoftwareInterrupt(long)
@ fastcall -stub  HalRequestSoftwareInterrupt(long)
@ fastcall -stub  HalSystemVectorDispatchEntry(long long long)
@ fastcall -stub  -arch=i386,arm KeAcquireInStackQueuedSpinLock(ptr ptr)
@ fastcall -stub  -arch=i386,arm KeAcquireInStackQueuedSpinLockRaiseToSynch(ptr ptr)
@ fastcall -stub  -arch=i386,arm KeAcquireQueuedSpinLock(ptr)
@ fastcall -stub  -arch=i386,arm KeAcquireQueuedSpinLockRaiseToSynch(ptr)
@ fastcall -stub  -arch=i386,arm KeAcquireSpinLockRaiseToSynch(ptr)
@ fastcall -stub  -arch=i386,arm KeReleaseInStackQueuedSpinLock(ptr)
@ fastcall -stub  -arch=i386,arm KeReleaseQueuedSpinLock(ptr long)
@ fastcall -stub  -arch=i386,arm KeTryToAcquireQueuedSpinLock(long ptr)
@ fastcall -stub  -arch=i386,arm KeTryToAcquireQueuedSpinLockRaiseToSynch(long ptr)
@ fastcall -stub  -arch=i386,arm KfAcquireSpinLock(ptr)
@ fastcall -stub  -arch=i386,arm KfLowerIrql(long)
@ fastcall -stub  -arch=i386,arm KfRaiseIrql(long)
@ fastcall -stub  -arch=i386,arm KfReleaseSpinLock(ptr long)
@ stdcall  -stub HalAcquireDisplayOwnership(ptr)
@ stdcall  -stub HalAdjustResourceList(ptr)
@ stdcall  -stub HalAllProcessorsStarted()
@ stdcall  -stub HalAllocateAdapterChannel(ptr ptr long ptr)
@ stdcall  -stub HalAllocateCommonBuffer(ptr long ptr long)
@ stdcall  -stub HalAllocateCrashDumpRegisters(ptr ptr)
@ stdcall  -stub HalAssignSlotResources(ptr ptr ptr ptr long long long ptr)
@ stdcall  -stub -arch=i386,arm HalBeginSystemInterrupt(long long ptr)
@ stub HalBugCheckSystem
@ stdcall -stub HalCalibratePerformanceCounter(ptr long long)
@ stub HalConvertDeviceIdtToIrql
@ stub HalDisableInterrupt
@ stdcall -stub HalDisplayString(str)
@ stub HalDynamicProcessorStarted
@ stub HalEnableInterrupt
@ stdcall -stub -arch=i386,arm HalEndSystemInterrupt(long long)
@ stub HalEnumerateEnvironmentVariablesEx
@ stdcall -stub HalFlushCommonBuffer(long long long long long)
@ stdcall -stub HalFreeCommonBuffer(ptr long long long ptr long)
@ stdcall -stub HalGetAdapter(ptr ptr)
@ stdcall -stub HalGetBusData(long long long ptr long)
@ stdcall -stub HalGetBusDataByOffset(long long long ptr long long)
@ stdcall -stub HalGetEnvironmentVariable(str long str)
@ stub HalGetEnvironmentVariableEx
@ stub HalGetInterruptTargetInformation
@ stdcall -stub HalGetInterruptVector(long long long long ptr ptr)
@ stub HalGetMessageRoutingInfo
@ stub HalGetVectorInput
@ stdcall -stub -arch=i386,x86_64 HalHandleNMI(ptr)
@ stdcall HalInitSystem(long ptr)
@ stdcall HalInitializeBios(long ptr)
@ stdcall HalInitializeProcessor(long ptr)
@ stdcall -stub HalMakeBeep(long)
@ stdcall -stub HalProcessorIdle()
@ stdcall -stub HalQueryDisplayParameters(ptr ptr ptr ptr)
@ stdcall -stub HalQueryRealTimeClock(ptr)
@ stdcall -stub HalReadDmaCounter(ptr)
@ stub HalRegisterErrataCallbacks
@ stdcall -stub HalReportResourceUsage()
@ stdcall -stub HalRequestIpi(long)
@ stdcall -stub HalReturnToFirmware(long)
@ stdcall -stub HalSetBusData(long long long ptr long)
@ stdcall -stub HalSetBusDataByOffset(long long long ptr long long)
@ stdcall -stub HalSetDisplayParameters(long long)
@ stdcall -stub HalSetEnvironmentVariable(str str)
@ stub HalSetEnvironmentVariableEx
@ stdcall -stub HalSetProfileInterval(long)
@ stdcall -stub HalSetRealTimeClock(ptr)
@ stdcall -stub HalSetTimeIncrement(long)
@ stub HalStartDynamicProcessor
@ stdcall -stub HalStartNextProcessor(ptr ptr)
@ stdcall -stub HalStartProfileInterrupt(long)
@ stdcall -stub HalStopProfileInterrupt(long)
@ stdcall -stub HalTranslateBusAddress(long long long long ptr ptr)
@ stdcall -stub -arch=i386,x86_64 IoAssignDriveLetters(ptr str ptr ptr)
@ stdcall -stub IoFlushAdapterBuffers(ptr ptr ptr ptr long long)
@ stdcall -stub IoFreeAdapterChannel(ptr)
@ stdcall -stub IoFreeMapRegisters(ptr ptr long)
@ stdcall -stub IoMapTransfer(ptr ptr ptr ptr ptr long)
@ stdcall -stub -arch=i386,x86_64 IoReadPartitionTable(ptr long long ptr)
@ stdcall -stub -arch=i386,x86_64 IoSetPartitionInformation(ptr long long long)
@ stdcall -stub -arch=i386,x86_64 IoWritePartitionTable(ptr long long long ptr)
@ extern KdComPortInUse
@ stdcall -stub -arch=i386,arm KeAcquireSpinLock(ptr ptr)
@ stdcall -stub KeFlushWriteBuffer()
@ stdcall -stub -arch=i386,arm KeGetCurrentIrql()
@ stdcall -stub -arch=i386,arm KeLowerIrql(long)
@ stdcall -stub KeQueryPerformanceCounter(ptr)
@ stdcall -stub -arch=i386,arm KeRaiseIrql(long ptr)
@ stdcall -stub -arch=i386,arm KeRaiseIrqlToDpcLevel()
@ stdcall -stub -arch=i386,arm KeRaiseIrqlToSynchLevel()
@ stdcall -stub -arch=i386,arm KeReleaseSpinLock(ptr long)
@ stdcall -stub KeStallExecutionProcessor(long)
@ stdcall -arch=i386,arm READ_PORT_BUFFER_UCHAR(ptr ptr long)
@ stdcall -arch=i386,arm READ_PORT_BUFFER_ULONG(ptr ptr long)
@ stdcall -arch=i386,arm READ_PORT_BUFFER_USHORT(ptr ptr long)
@ stdcall -arch=i386,arm READ_PORT_UCHAR(ptr)
@ stdcall -arch=i386,arm READ_PORT_ULONG(ptr)
@ stdcall -arch=i386,arm READ_PORT_USHORT(ptr)
@ stdcall -arch=i386,arm WRITE_PORT_BUFFER_UCHAR(ptr ptr long)
@ stdcall -arch=i386,arm WRITE_PORT_BUFFER_ULONG(ptr ptr long)
@ stdcall -arch=i386,arm WRITE_PORT_BUFFER_USHORT(ptr ptr long)
@ stdcall -arch=i386,arm WRITE_PORT_UCHAR(ptr long)
@ stdcall -arch=i386,arm WRITE_PORT_ULONG(ptr long)
@ stdcall -arch=i386,arm WRITE_PORT_USHORT(ptr long)
@ stdcall -version=0x0502 -arch=x86_64 x86BiosAllocateBuffer(ptr ptr ptr)
@ stdcall -version=0x0600+ -arch=i386,x86_64 x86BiosAllocateBuffer(ptr ptr ptr)
@ stdcall -version=0x0502 -arch=x86_64 x86BiosCall(long ptr)
@ stdcall -version=0x0600+ -arch=i386,x86_64 x86BiosCall(long ptr)
@ stdcall -version=0x0502 -arch=x86_64 x86BiosFreeBuffer(long long)
@ stdcall -version=0x0600+ -arch=i386,x86_64 x86BiosFreeBuffer(long long)
@ stdcall -version=0x0502 -arch=x86_64 x86BiosReadMemory(long long ptr long)
@ stdcall -version=0x0600+ -arch=i386,x86_64 x86BiosReadMemory(long long ptr long)
@ stdcall -version=0x0502 -arch=x86_64 x86BiosWriteMemory(long long ptr long)
@ stdcall -version=0x0600+ -arch=i386,x86_64 x86BiosWriteMemory(long long ptr long)
