@ stdcall -stub NotifyAllocate()
@ stdcall -stub NotifyExecute()
@ stdcall -stub NotifyFree()
@ stdcall -stub NotifyLoadConfiguration()
@ stdcall -stub NotifyLogon()
@ stdcall -stub NotifyMemSize()
@ stdcall -stub NotifyReportEvent()
@ stdcall -stub NotifyUnloadConfiguration()